### ISSUE TITLE
fail to install on ubuntu arm

### ISSUE THREAD

**Issue by kewogc** [gdbtek/linux-cookbooks#20]
root@kew:~# ubuntu-cookbooks/cookbooks/nginx/recipes/install.bash
"FATAL : non 'Ubuntu' OS found"

root@kew:~# uname --a
Linux kew 4.1.6-249 #1 SMP Mon Aug 31 12:34:47 UTC 2015 armv7l armv7l armv7l GNU/Linux

**Comment by gdbtek** [comment]
@kewogc  I don't support Ubuntu ARM yet, as matter fact, I have no idea how to install it. There is a way you can try following to see if Nginx cookbook works for you by:

1) removing `checkRequireSystem` from https://github.com/gdbtek/ubuntu-cookbooks/blob/master/cookbooks/nginx/recipes/install.bash#L83 to by pass OS validation or 
2) Update https://github.com/gdbtek/ubuntu-cookbooks/blob/master/libraries/util.bash#L1296 to search for `armv7` instead of `ubuntu`

Hope this helps and let me know what you find. Thanks. Closing this issue.
